server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8081

metrics:
  frequency: 1 minute
  reporters:
    - type: console
      timeZone: UTC
      output: stdout
